jobs:
  main:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./check/run

name: Workflow

on:
  schedule:
    - cron: "5 */2 * * *"
